name: Build and deploy Python app to Azure Web App - api-sz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - uses: actions/checkout@v4

      # Configura la versión de Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Crea y activa el entorno virtual
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      # Instala las dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Comprime los archivos para el despliegue
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # Carga el artefacto para la etapa de despliegue
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Descarga el artefacto del trabajo de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Descomprime los archivos del artefacto
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Despliega la aplicación en Azure
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'api-sz'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DFBB7B97C5884C3CA72A7B114638D153 }}
          startup-command: 'python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT'
