name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main  # O la rama que quieras desplegar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Selecciona la versión de Python que usa Azure

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "API-SZ"  # Reemplaza con el nombre de tu aplicación
        slot-name: "development"  # Slot de producción
        pscm-url: 'https://API-SZ.scm.azurewebsites.net'
        package: '.'
